### ISSUE TITLE
About angular-bootstrap $uibmodal resolve annotate!

### ISSUE THREAD

**Issue by mrdulin** [mgol/grunt-ng-annotate#50] opened 2016-04-08 09:10 UTC
![image](https://cloud.githubusercontent.com/assets/17866683/14379419/742f8c84-fdac-11e5-831e-8d9d65a28ecc.png)

It seems that $uibmodal resolve can not be annotated.

![image](https://cloud.githubusercontent.com/assets/17866683/14379443/9777d96c-fdac-11e5-8275-cc5fea06f98c.png)

I use yeoman's generator-angular 0.15.1

help me please~

**Comment by mgol** [comment] 2016-04-08 09:25
This may be a duplicate of https://github.com/olov/ng-annotate/issues/150. In any case, please report issues with output at https://github.com/olov/ng-annotate/issues/, this project is just a wrapper Grunt plugin.

**Closed by mgol** 2016-04-08 09:25 UTC

**Comment by mrdulin** [comment] 2016-04-08 10:23
@mgol Thanks! It seems the ng-annotate does not support custom directive.

so, Maybe I have to use `['xxx', function(xxx) { ... }]` manually.

**Comment by mgol** [comment] 2016-04-08 10:56
As described in the issue, in almost all cases you can use `'ngInject';` instead of annotating it yourself.
